// This file was auto-generated by prost-build from proto/autocomplete.proto
// Manual changes may be overwritten

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordEntry {
    #[prost(string, tag = "1")]
    pub term: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub frequency: u32,
    #[prost(string, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordBatch {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<WordEntry>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AutocompleteRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub max_results: u32,
    #[prost(bool, tag = "3")]
    pub use_wheeler: bool,
    #[prost(uint32, tag = "4")]
    pub wheeler_max_distance: u32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AutocompleteResult {
    #[prost(string, tag = "1")]
    pub term: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub score: u32,
    #[prost(bool, tag = "3")]
    pub is_prefix_match: bool,
    #[prost(bool, tag = "4")]
    pub is_wheeler_match: bool,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AutocompleteResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<AutocompleteResult>,
    #[prost(uint32, tag = "2")]
    pub prefix_matches: u32,
    #[prost(uint32, tag = "3")]
    pub wheeler_matches: u32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildTrieRequest {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<WordBatch>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub word_count: u32,
}
