/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Expense_formRouteImport } from './routes/expense_form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatbotReportingRouteImport } from './routes/chatbot/reporting'
import { Route as ChatbotPlanningRouteImport } from './routes/chatbot/planning'
import { Route as ChatbotOperationRouteImport } from './routes/chatbot/operation'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Expense_formRoute = Expense_formRouteImport.update({
  id: '/expense_form',
  path: '/expense_form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotReportingRoute = ChatbotReportingRouteImport.update({
  id: '/chatbot/reporting',
  path: '/chatbot/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotPlanningRoute = ChatbotPlanningRouteImport.update({
  id: '/chatbot/planning',
  path: '/chatbot/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotOperationRoute = ChatbotOperationRouteImport.update({
  id: '/chatbot/operation',
  path: '/chatbot/operation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense_form': typeof Expense_formRoute
  '/login': typeof LoginRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/chatbot/operation': typeof ChatbotOperationRoute
  '/chatbot/planning': typeof ChatbotPlanningRoute
  '/chatbot/reporting': typeof ChatbotReportingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expense_form': typeof Expense_formRoute
  '/login': typeof LoginRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/chatbot/operation': typeof ChatbotOperationRoute
  '/chatbot/planning': typeof ChatbotPlanningRoute
  '/chatbot/reporting': typeof ChatbotReportingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense_form': typeof Expense_formRoute
  '/login': typeof LoginRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/chatbot/operation': typeof ChatbotOperationRoute
  '/chatbot/planning': typeof ChatbotPlanningRoute
  '/chatbot/reporting': typeof ChatbotReportingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense_form'
    | '/login'
    | '/records'
    | '/signup'
    | '/chatbot/operation'
    | '/chatbot/planning'
    | '/chatbot/reporting'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expense_form'
    | '/login'
    | '/records'
    | '/signup'
    | '/chatbot/operation'
    | '/chatbot/planning'
    | '/chatbot/reporting'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/expense_form'
    | '/login'
    | '/records'
    | '/signup'
    | '/chatbot/operation'
    | '/chatbot/planning'
    | '/chatbot/reporting'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Expense_formRoute: typeof Expense_formRoute
  LoginRoute: typeof LoginRoute
  RecordsRoute: typeof RecordsRoute
  SignupRoute: typeof SignupRoute
  ChatbotOperationRoute: typeof ChatbotOperationRoute
  ChatbotPlanningRoute: typeof ChatbotPlanningRoute
  ChatbotReportingRoute: typeof ChatbotReportingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense_form': {
      id: '/expense_form'
      path: '/expense_form'
      fullPath: '/expense_form'
      preLoaderRoute: typeof Expense_formRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot/reporting': {
      id: '/chatbot/reporting'
      path: '/chatbot/reporting'
      fullPath: '/chatbot/reporting'
      preLoaderRoute: typeof ChatbotReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot/planning': {
      id: '/chatbot/planning'
      path: '/chatbot/planning'
      fullPath: '/chatbot/planning'
      preLoaderRoute: typeof ChatbotPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot/operation': {
      id: '/chatbot/operation'
      path: '/chatbot/operation'
      fullPath: '/chatbot/operation'
      preLoaderRoute: typeof ChatbotOperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Expense_formRoute: Expense_formRoute,
  LoginRoute: LoginRoute,
  RecordsRoute: RecordsRoute,
  SignupRoute: SignupRoute,
  ChatbotOperationRoute: ChatbotOperationRoute,
  ChatbotPlanningRoute: ChatbotPlanningRoute,
  ChatbotReportingRoute: ChatbotReportingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
