name: Upload YOLO ONNX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  upload-onnx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Verify ONNX exists
        run: |
          ls -lh mlruns/0/models/m-e253840b5b2f4e09b74252ddda4cc6b2/artifacts/artifacts/receipt-yolo.onnx

      - name: Upload ONNX artifact
        uses: actions/upload-artifact@v4
        with:
          name: yolo-onnx_${{ env.TODAY }}
          path: mlruns/0/models/m-e253840b5b2f4e09b74252ddda4cc6b2/artifacts/artifacts/receipt-yolo.onnx
          retention-days: 3
